### PR TITLE
uwu?

### PR DESCRIPTION
**Pull request by ghost**
user you are going to hate me for this lmao

### CODE REVIEW

**Comment by User9684** [comment]
Man

**Comment by User9684** [comment]
Ok

**Comment by ghost** [comment]
Fallen07012021hsT_NC-sudo_apt-get_install_friends

**Comment by FxllenCode** [comment]
bro?!?

**Comment by ProjectHSI** [comment]
User and Fxllen go on accept it
this is the ultimate pr

**Comment by BloxTobal** [comment]
Lol

**Comment by GnomeDevs** [comment]
I hate you so much

**Review by BobbedBob — APPROVED** [review]

**Review by User9684 — CHANGES_REQUESTED** [review]
doesn’t even have the new strings

**Comment by ghost** [comment]
it does now nerd

**Review by User9684 — CHANGES_REQUESTED** [review]
Some of these could be more furrified, if you're gonna make a furry lang you might as well go all out, yknow?
for example:
Time -> Twime

Hell, you might aswell add some emoticons at this point.

**Comment by BobbedBob** [comment]
great PR

**Pull request merged**
