### PR TITLE
Add/translated the new strings on PT.json

### PR DESCRIPTION
**Pull request by MatadorProBr**
Maybe it requires some revision

### CODE REVIEW

**Comment by User9684** [comment]
There are some other new strings aswell, check EN.json

**Comment by User9684** [comment]
wait no im blind as fuck

**Review by User9684 — CHANGES_REQUESTED** [review]
Looks good, but you need to add the new FFlag default messages, besides that everything is fine from what I can understand.

**Review by MatadorProBr — COMMENTED** [review]
Done

**Review by User9684 — APPROVED** [review]

**Pull request merged**
