### PR TITLE
Create PH.json

### PR DESCRIPTION
**Pull request by totoygamingyt**
some words may incorrect cuz im bad in translation

### CODE REVIEW

**Comment by FxllenCode** [comment]
Thanks for the contribution! 

We'll let it sit for a little to see if anyone wants to review it before we merge.

**Comment by zapacni** [comment]
FYI the language code for Tagalog according to the ISO 639-1 standard (which this repo follows) is TL. Unfortunately I don't speak Tagalog so I won't be able to contribute on that end, but you may want to correct this for consistency throughout the repo.

**Review by FxllenCode — CHANGES_REQUESTED** [review]
Please rename it to TL.json and then we'll be good!

**Comment by totoygamingyt** [comment]
done <3

**Review by FxllenCode — APPROVED** [review]

**Comment by FxllenCode** [comment]
Thanks!

**Pull request merged**
