### PR TITLE
Spanish translations

### PR DESCRIPTION
**Pull request by IJustDavi**
Outage + FFlag strings translated to spanish.

### CODE REVIEW

**Comment by User9684** [comment]
Currently getting this verified with another person. Thanks!

**Comment by FxllenCode** [comment]
Waiting for someone to review it before merging. Thanks!

**Comment by User9684** [comment]
Alright, according to second opinion;
```
first one is "al vuelto"
for the second one replace "su" to "el"
6th line the same, replace "su" to "el"
```

**Comment by jc-discdev** [comment]
> Alright, according to second opinion;
> 
> ```
> 
> first one is "al vuelto"
> 
> for the second one replace "su" to "el"
> 
> 6th line the same, replace "su" to "el"
> 
> ```

As I checked by myself (I'm from Spain lol) its ok the translation.

**Pull request merged**
